import { Service, Professional, Patient, Booking, MedicalReport, Review, LabTest, LabInfo } from '../types';

export const initialServices: Service[] = [
  {
    id: 'srv-1',
    name: 'General Health Checkup',
    category: 'Full Body & Preventive',
    description: 'Comprehensive physical examination and vital signs review conducted in the privacy and comfort of your home by a licensed clinician.',
    inclusions: [
      'Complete vitals check (BP, SpO2, Heart Rate, Temperature, BMI)',
      'Systematic organ evaluation (Chest, Abdomen, ENT)',
      'Lifestyle & metabolic risk profiling',
      'Clinical consultation & digital report summary',
    ],
    durationMinutes: 45,
    price: 699,
    preparationInstructions: [
      'Keep past medical records, prescriptions, and recent lab reports ready.',
      'Ensure a quiet, well-lit room for examination.',
      'Avoid heavy caffeine consumption 1 hour prior to visit.',
    ],
    popular: true,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-2',
    name: 'Blood Sample Collection',
    category: 'Diagnostic & Lab',
    description: 'Painless, certified phlebotomy service at your doorstep using vacutainer tubes and strict cold-chain sample preservation transport.',
    inclusions: [
      'Doorstep sample collection by certified phlebotomist',
      'Barcoded, sterile vacuum tubes for zero-contamination',
      'Temperature-controlled cold-chain specimen transit',
      'Digital laboratory report delivered within 12-24 hours',
    ],
    durationMinutes: 20,
    price: 249,
    preparationInstructions: [
      'Overnight fasting (10-12 hours) recommended if getting Fasting Sugar or Lipid profile.',
      'Drink 1-2 glasses of plain water before collection to ease venipuncture.',
      'Rest comfortably 5 minutes before the phlebotomist arrives.',
    ],
    popular: true,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-3',
    name: 'Blood Pressure Check & Monitoring',
    category: 'Vitals & Routine',
    description: 'Accurate clinical blood pressure assessment, multiple posture readings, and cardiovascular guidance by a qualified nurse.',
    inclusions: [
      'Triplicate calibrated BP measurements in sitting and lying postures',
      'Pulse rhythm and regularity assessment',
      'Cardiovascular lifestyle counselling',
      'Hypertension tracking chart provided',
    ],
    durationMinutes: 20,
    price: 199,
    preparationInstructions: [
      'Sit comfortably and relax for at least 10 minutes before the appointment.',
      'Avoid smoking, exercise, and caffeine for 30 minutes prior.',
      'Keep your current anti-hypertensive medication names handy.',
    ],
    popular: false,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-4',
    name: 'Blood Sugar Test (Fasting & PP)',
    category: 'Diagnostic & Lab',
    description: 'Instant bedside blood glucose screening (Fasting, Random, or Post-Prandial) with immediate digital record generation.',
    inclusions: [
      'Laboratory-grade glucometer testing with fresh sterile lancet',
      'Pre-meal and post-meal glucose recording',
      'Dietary and hypoglycaemia safety advice',
      'Instant result documentation',
    ],
    durationMinutes: 15,
    price: 149,
    preparationInstructions: [
      'For fasting test: 8-10 hours fasting without food or milk.',
      'For PP test: Exactly 2 hours after starting your meal.',
      'Notify the clinician of current insulin or oral hypoglycaemic dosages.',
    ],
    popular: false,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-5',
    name: '12-Lead ECG at Home',
    category: 'Cardiac & Special',
    description: 'Hospital-grade 12-lead portable Electrocardiogram conducted in bed, with instantaneous cardiologist-reviewed interpretation report.',
    inclusions: [
      'Full 12-lead diagnostic portable ECG procedure',
      'Conducted by trained cardiac emergency technician',
      'Instant digitized tracing with remote cardiologist sign-off',
      'Immediate referral protocol if acute rhythm anomalies detected',
    ],
    durationMinutes: 30,
    price: 799,
    preparationInstructions: [
      'Wear loose, two-piece clothing for easy electrode placement.',
      'Avoid applying skin lotions, creams, or oils on chest and limbs.',
      'Remove metallic jewellery or watches before the test.',
    ],
    popular: true,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-6',
    name: 'Elderly Health & Mobility Checkup',
    category: 'Geriatric Care',
    description: 'Specialized geriatric wellness visit focused on dementia screening, fall risk assessment, polypharmacy review, and joint mobility.',
    inclusions: [
      'Comprehensive functional mobility and fall-risk audit',
      'Memory and cognitive baseline screening',
      'Medication cross-interaction review',
      'Home safety hazard recommendations for family caregivers',
    ],
    durationMinutes: 60,
    price: 999,
    preparationInstructions: [
      'A primary family member or caregiver is requested to be present.',
      'Keep all ongoing daily medication boxes visible on a table.',
      'Prepare list of past surgeries, hospitalizations, and mobility aids used.',
    ],
    popular: true,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-7',
    name: 'Doctor Home Visit (General Physician)',
    category: 'Doctor Consultations',
    description: 'Thorough in-person home visit by an MD/MBBS doctor for acute illnesses, chronic disease follow-ups, and doorstep treatment planning.',
    inclusions: [
      'In-depth 45-minute clinical bedside consultation',
      'Physical examination, chest auscultation, abdominal palpation',
      'Prescription writing with drug dosages & dietary instructions',
      'Referral or escalation guidance if secondary care is required',
    ],
    durationMinutes: 45,
    price: 1199,
    preparationInstructions: [
      'List all current symptoms in sequence of onset.',
      'Have past surgical notes and discharge summaries accessible.',
      'Ensure patient is in a comfortable resting position.',
    ],
    popular: true,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'srv-8',
    name: 'Nursing Visit (Wound Dressing & Injections)',
    category: 'Nursing & Procedures',
    description: 'Skilled nursing intervention for post-surgical sterile wound dressing, IV/IM injections, catheter management, or nebulization.',
    inclusions: [
      'Aseptic wound dressing using hospital-grade sterile kit',
      'Prescribed IV/IM/Subcutaneous injection administration',
      'Catheter care or tracheostomy hygiene assistance',
      'Bedside vitals and recovery stage assessment',
    ],
    durationMinutes: 40,
    price: 499,
    preparationInstructions: [
      'Valid doctor prescription for medication or dressing must be provided.',
      'Keep sterile dressing consumables or prescribed ampoules ready.',
      'Maintain clean, sanitized handwashing facility for the visiting nurse.',
    ],
    popular: false,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1584432810601-6c7f27d2362b?auto=format&fit=crop&w=800&q=80',
  },
];

export const initialProfessionals: Professional[] = [
  {
    id: 'pro-1',
    userId: 'user-pro-1',
    name: 'Dr. Aisha Sharma, MD',
    role: 'Doctor',
    phone: '+91 98201 11223',
    email: 'dr.aisha.sharma@trustpatholab.internal',
    qualification: 'MBBS, MD (Internal Medicine)',
    experienceYears: 11,
    serviceTypes: ['srv-1', 'srv-6', 'srv-7'],
    serviceArea: 'Central & Downtown Districts',
    isAvailable: true,
    isVerified: true,
    rating: 4.95,
    totalVisits: 342,
    profilePhoto: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'pro-2',
    userId: 'user-pro-2',
    name: 'Sister Sunita Rao, B.Sc Nursing',
    role: 'Nurse',
    phone: '+91 98202 22334',
    email: 'sunita.rao@trustpatholab.internal',
    qualification: 'B.Sc Nursing, Critical Care Certified',
    experienceYears: 8,
    serviceTypes: ['srv-3', 'srv-4', 'srv-8', 'srv-1'],
    serviceArea: 'West & Suburban Sectors',
    isAvailable: true,
    isVerified: true,
    rating: 4.92,
    totalVisits: 512,
    profilePhoto: 'https://images.unsplash.com/photo-1594824813576-90f7a552ee01?auto=format&fit=crop&w=400&q=80',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'pro-3',
    userId: 'user-pro-3',
    name: 'Rohan Deshmukh, DMLT',
    role: 'Lab Technician',
    phone: '+91 98203 33445',
    email: 'rohan.deshmukh@trustpatholab.internal',
    qualification: 'Diploma in Medical Laboratory Technology',
    experienceYears: 6,
    serviceTypes: ['srv-2', 'srv-4', 'srv-5'],
    serviceArea: 'All City Metro Zones',
    isAvailable: true,
    isVerified: true,
    rating: 4.88,
    totalVisits: 720,
    profilePhoto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    createdAt: '2025-02-10T00:00:00Z',
  },
  {
    id: 'pro-4',
    userId: 'user-pro-4',
    name: 'Dr. Vikramaditya Sen, MS',
    role: 'Doctor',
    phone: '+91 98204 44556',
    email: 'dr.vikram.sen@trustpatholab.internal',
    qualification: 'MBBS, MS, Family Medicine Fellowship',
    experienceYears: 14,
    serviceTypes: ['srv-1', 'srv-7'],
    serviceArea: 'North Sector & Riverside',
    isAvailable: true,
    isVerified: true,
    rating: 4.98,
    totalVisits: 280,
    profilePhoto: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'pro-5',
    userId: 'user-pro-5',
    name: 'Rahul Nair, GNM',
    role: 'Elderly Care Specialist',
    phone: '+91 98205 55667',
    email: 'rahul.nair@trustpatholab.internal',
    qualification: 'GNM, Geriatric Rehabilitation Certified',
    experienceYears: 7,
    serviceTypes: ['srv-6', 'srv-8', 'srv-3'],
    serviceArea: 'East & Tech Corridor Zones',
    isAvailable: true,
    isVerified: true,
    rating: 4.89,
    totalVisits: 410,
    profilePhoto: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const initialPatients: Patient[] = [
  {
    id: 'pat-1',
    userId: 'user-pat-1',
    fullName: 'Rajesh Verma',
    age: 48,
    gender: 'male',
    phone: '+91 98765 43210',
    email: 'rajesh.verma@example.com',
    emergencyContact: '+91 98765 43219 (Wife: Sunita)',
    medicalNotes: 'Type-2 Diabetes under Metformin; Mild hypertension.',
    createdAt: '2025-03-10T00:00:00Z',
  },
  {
    id: 'pat-2',
    userId: 'user-pat-2',
    fullName: 'Kamla Devi',
    age: 74,
    gender: 'female',
    phone: '+91 98111 22334',
    email: 'kamla.devi@example.com',
    emergencyContact: '+91 98111 99887 (Son: Amit)',
    medicalNotes: 'Osteoarthritis in both knees, history of mild vertigo, restricted mobility.',
    createdAt: '2025-03-12T00:00:00Z',
  },
  {
    id: 'pat-3',
    userId: 'user-pat-3',
    fullName: 'Arun Iyer',
    age: 34,
    gender: 'male',
    phone: '+91 98222 33445',
    email: 'arun.iyer@example.com',
    emergencyContact: '+91 98222 88776 (Sister: Priya)',
    medicalNotes: 'Post-operative ACL knee reconstruction; requires periodic dressing.',
    createdAt: '2025-03-15T00:00:00Z',
  },
  {
    id: 'pat-4',
    userId: 'user-pat-4',
    fullName: 'Meenakshi Sundaram',
    age: 52,
    gender: 'female',
    phone: '+91 98333 44556',
    email: 'meenakshi@example.com',
    emergencyContact: '+91 98333 77665 (Spouse: Sundaram)',
    medicalNotes: 'Hypothyroidism under daily Eltroxin 50mcg.',
    createdAt: '2025-03-18T00:00:00Z',
  },
  {
    id: 'pat-5',
    userId: 'user-pat-5',
    fullName: 'Gurpreet Singh',
    age: 62,
    gender: 'male',
    phone: '+91 98444 55667',
    email: 'gurpreet.singh@example.com',
    emergencyContact: '+91 98444 66554 (Daughter: Jaspreet)',
    medicalNotes: 'Essential hypertension; routine cardiac follow-up needed.',
    createdAt: '2025-03-20T00:00:00Z',
  },
  {
    id: 'pat-6',
    userId: 'user-pat-6',
    fullName: 'Ananya Roy',
    age: 29,
    gender: 'female',
    phone: '+91 98555 66778',
    email: 'ananya.roy@example.com',
    emergencyContact: '+91 98555 55443 (Father: Debashish)',
    medicalNotes: 'Severe seasonal allergy and intermittent migraine.',
    createdAt: '2025-03-22T00:00:00Z',
  },
  {
    id: 'pat-7',
    userId: 'user-pat-7',
    fullName: 'Vikram Patel',
    age: 41,
    gender: 'male',
    phone: '+91 98666 77889',
    email: 'vikram.patel@example.com',
    emergencyContact: '+91 98666 44332 (Wife: Bhavna)',
    medicalNotes: 'Executive annual health check screening.',
    createdAt: '2025-03-24T00:00:00Z',
  },
  {
    id: 'pat-8',
    userId: 'user-pat-8',
    fullName: 'Savita Kulkarni',
    age: 68,
    gender: 'female',
    phone: '+91 98777 88990',
    email: 'savita.kulkarni@example.com',
    emergencyContact: '+91 98777 33221 (Son: Rahul)',
    medicalNotes: 'Hypertension and mild diabetic neuropathy.',
    createdAt: '2025-03-25T00:00:00Z',
  },
  {
    id: 'pat-9',
    userId: 'user-pat-9',
    fullName: 'Farhan Akhtar Siddiqui',
    age: 38,
    gender: 'male',
    phone: '+91 98888 99001',
    email: 'farhan.siddiqui@example.com',
    emergencyContact: '+91 98888 22110 (Brother: Tariq)',
    medicalNotes: 'Fever and throat pain for 3 days; requires physician consult.',
    createdAt: '2025-03-28T00:00:00Z',
  },
  {
    id: 'pat-10',
    userId: 'user-pat-10',
    fullName: 'Pooja Hegde',
    age: 26,
    gender: 'female',
    phone: '+91 98999 00112',
    email: 'pooja.hegde@example.com',
    emergencyContact: '+91 98999 11009 (Mother: Rekha)',
    medicalNotes: 'Routine comprehensive lipid and vitamin D blood panel.',
    createdAt: '2025-03-30T00:00:00Z',
  },
];

export const initialBookings: Booking[] = [
  {
    id: 'book-101',
    bookingCode: 'CP-2601-984',
    patientId: 'pat-1',
    patientName: 'Rajesh Verma',
    patientPhone: '+91 98765 43210',
    patientAge: 48,
    patientGender: 'male',
    emergencyContact: '+91 98765 43219 (Wife: Sunita)',
    medicalNotes: 'History of elevated post-prandial blood sugar.',
    serviceId: 'srv-1',
    serviceName: 'General Health Checkup',
    serviceCategory: 'Full Body & Preventive',
    address: {
      houseFlat: 'Flat 402, Greenfield Meadows',
      street: '14th Cross Road',
      area: 'Indira Nagar',
      city: 'Bangalore',
      state: 'Karnataka',
      pinCode: '560038',
      landmark: 'Near BDA Complex & Cafe Coffee Day',
      instructions: 'Ring bell twice; lift available on left.',
    },
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    timeSlot: '09:00 AM - 10:00 AM',
    price: 699,
    status: 'assigned',
    paymentStatus: 'success',
    paymentId: 'pay-txn-8801',
    assignedProfessionalId: 'pro-1',
    assignedProfessional: initialProfessionals[0],
    createdAt: '2026-10-04T08:30:00Z',
    updatedAt: '2026-10-04T09:15:00Z',
  },
  {
    id: 'book-102',
    bookingCode: 'CP-2602-552',
    patientId: 'pat-2',
    patientName: 'Kamla Devi',
    patientPhone: '+91 98111 22334',
    patientAge: 74,
    patientGender: 'female',
    emergencyContact: '+91 98111 99887 (Son: Amit)',
    medicalNotes: 'Patient cannot climb stairs; needs caregiver assistance during mobility test.',
    serviceId: 'srv-6',
    serviceName: 'Elderly Health & Mobility Checkup',
    serviceCategory: 'Geriatric Care',
    address: {
      houseFlat: 'House #12, Rose Villa',
      street: 'Vasant Vihar Avenue',
      area: 'South Delhi',
      city: 'New Delhi',
      state: 'Delhi',
      pinCode: '110057',
      landmark: 'Opposite Community Park Gate 2',
      instructions: 'Ground floor residence. Call son before arrival.',
    },
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: '11:00 AM - 12:00 PM',
    price: 999,
    status: 'on_the_way',
    paymentStatus: 'success',
    paymentId: 'pay-txn-8802',
    assignedProfessionalId: 'pro-5',
    assignedProfessional: initialProfessionals[4],
    createdAt: '2026-10-04T10:00:00Z',
    updatedAt: '2026-10-05T05:30:00Z',
  },
  {
    id: 'book-103',
    bookingCode: 'CP-2603-129',
    patientId: 'pat-3',
    patientName: 'Arun Iyer',
    patientPhone: '+91 98222 33445',
    patientAge: 34,
    patientGender: 'male',
    emergencyContact: '+91 98222 88776',
    medicalNotes: 'Post ACL surgery day 12 sterile dressing change.',
    serviceId: 'srv-8',
    serviceName: 'Nursing Visit (Wound Dressing & Injections)',
    serviceCategory: 'Nursing & Procedures',
    address: {
      houseFlat: 'Tower B, Flat 1204, Lodha Bellissimo',
      street: 'N.M. Joshi Marg',
      area: 'Mahalaxmi',
      city: 'Mumbai',
      state: 'Maharashtra',
      pinCode: '400011',
      landmark: 'Near Mahalaxmi Railway Station',
      instructions: 'Collect visitor pass at security gate.',
    },
    date: '2026-10-03',
    timeSlot: '04:00 PM - 05:00 PM',
    price: 499,
    status: 'completed',
    paymentStatus: 'success',
    paymentId: 'pay-txn-8803',
    assignedProfessionalId: 'pro-2',
    assignedProfessional: initialProfessionals[1],
    createdAt: '2026-10-02T11:00:00Z',
    updatedAt: '2026-10-03T17:30:00Z',
  },
  {
    id: 'book-104',
    bookingCode: 'CP-2604-741',
    patientId: 'pat-4',
    patientName: 'Meenakshi Sundaram',
    patientPhone: '+91 98333 44556',
    patientAge: 52,
    patientGender: 'female',
    emergencyContact: '+91 98333 77665',
    medicalNotes: 'Fasting lipid profile and thyroid function test.',
    serviceId: 'srv-2',
    serviceName: 'Blood Sample Collection',
    serviceCategory: 'Diagnostic & Lab',
    address: {
      houseFlat: 'Apt 2B, Lakshmi Enclave',
      street: 'T. Nagar Main Road',
      area: 'T. Nagar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600017',
      landmark: 'Next to Saravana Stores',
      instructions: 'Please arrive sharp at 7 AM for fasting sample.',
    },
    date: new Date(Date.now() + 172800000).toISOString().split('T')[0], // Day after tomorrow
    timeSlot: '07:00 AM - 08:00 AM',
    price: 249,
    status: 'confirmed',
    paymentStatus: 'success',
    paymentId: 'pay-txn-8804',
    createdAt: '2026-10-05T02:00:00Z',
    updatedAt: '2026-10-05T02:05:00Z',
  },
  {
    id: 'book-105',
    bookingCode: 'CP-2605-316',
    patientId: 'pat-9',
    patientName: 'Farhan Akhtar Siddiqui',
    patientPhone: '+91 98888 99001',
    patientAge: 38,
    patientGender: 'male',
    emergencyContact: '+91 98888 22110',
    medicalNotes: 'Fever 101.4 F, sore throat, severe body aches.',
    serviceId: 'srv-7',
    serviceName: 'Doctor Home Visit (General Physician)',
    serviceCategory: 'Doctor Consultations',
    address: {
      houseFlat: 'Plot 88, Banjara Hills Road #3',
      street: 'Banjara Hills',
      area: 'Central Zone',
      city: 'Hyderabad',
      state: 'Telangana',
      pinCode: '500034',
      landmark: 'Behind Park Hyatt Hotel',
      instructions: 'Security guard will direct to private bungalow.',
    },
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: '02:00 PM - 03:00 PM',
    price: 1199,
    status: 'in_progress',
    paymentStatus: 'success',
    paymentId: 'pay-txn-8805',
    assignedProfessionalId: 'pro-4',
    assignedProfessional: initialProfessionals[3],
    createdAt: '2026-10-05T06:00:00Z',
    updatedAt: '2026-10-05T08:30:00Z',
  },
];

export const initialReports: MedicalReport[] = [
  {
    id: 'rep-301',
    bookingId: 'book-103',
    patientId: 'pat-3',
    professionalId: 'pro-2',
    professionalName: 'Sister Sunita Rao, B.Sc Nursing',
    professionalRole: 'Registered Critical Care Nurse',
    serviceName: 'Nursing Visit (Wound Dressing & Injections)',
    visitDate: '2026-10-03',
    vitals: {
      bloodPressure: '118/76 mmHg',
      pulseRate: 72,
      temperature: '98.4 °F',
      spO2: 99,
    },
    observations: 'Surgical incision over right knee appears clean with dry edges. No erythema, localized heat, or purulent exudate detected. Staples intact. Sterile dressing renewed with silver sulfadiazine gauze and micropore taping.',
    prescriptions: [
      {
        id: 'rx-1',
        medicineName: 'Cefuroxime Axetil',
        dosage: '500 mg',
        frequency: 'Twice daily after meals',
        duration: '3 more days',
        notes: 'Complete remaining antibiotic course without skipping.',
      },
      {
        id: 'rx-2',
        medicineName: 'Paracetamol',
        dosage: '650 mg',
        frequency: 'SOS (Only if pain > 5/10)',
        duration: 'As needed',
        notes: 'Max 3 tablets in 24 hours.',
      },
    ],
    doctorNotes: 'Advised strict non-weight bearing on operated limb with walker support. Schedule staple removal in 4 days.',
    verifiedSignature: true,
    createdAt: '2026-10-03T17:30:00Z',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'book-103',
    patientName: 'Arun Iyer',
    serviceName: 'Nursing Visit (Wound Dressing)',
    rating: 5,
    comment: 'Nurse Sunita was gentle, ultra-hygienic, and arrived right on the dot. My surgical wound dressing was done seamlessly without any pain!',
    createdAt: '2026-10-03T18:15:00Z',
  },
  {
    id: 'rev-2',
    bookingId: 'book-099',
    patientName: 'Priya Narayanan',
    serviceName: 'Elderly Health Checkup',
    rating: 5,
    comment: 'Booked an elderly checkup for my 82-year-old mother. The doctor spent 50 minutes explaining her medications and tested her mobility with immense patience.',
    createdAt: '2026-09-28T14:20:00Z',
  },
  {
    id: 'rev-3',
    bookingId: 'book-098',
    patientName: 'Vikas Malhotra',
    serviceName: '12-Lead ECG at Home',
    rating: 5,
    comment: 'Getting a 12-lead ECG in bed within 2 hours of booking was life-saving for my father. The digital report with cardiologist sign-off came instantly.',
    createdAt: '2026-09-25T11:45:00Z',
  },
];

export const officialLabInfo: LabInfo = {
  name: 'Trust Patho Lab',
  subtitle: 'Pathology Laboratory',
  registrationNo: '229112131723',
  address: 'Gaya Patna Road, Iqbal Nagar, Near Karbala, Gaya – 823002, Bihar',
  phones: ['6206175583', '6299476228', '9142661354'],
  whatsapp: '6206175583',
  established: '2024',
  services: [
    'Haematology',
    'Serology',
    'Hormones',
    'Biochemistry',
    'Fluid Analysis',
    'Histopathology',
    'Immunology',
    'FNAC',
  ],
  features: [
    '24/7 Hour Service',
    'Home Sample Collection Facility Available',
    'Multi-Brand Special Pathological Tests',
  ],
  disclaimer: 'This report is only for a profession opinion co-relate clinically. Not to be used for medico legal purpose',
};

export const initialLabTests: LabTest[] = [
  // Left Column from Price List Image
  { id: 'test-001', slNo: 1, code: 'CBC', name: 'CBC', fullName: 'Complete Blood Count (Haemogram)', category: 'Haematology', price: 350, sampleType: 'EDTA Whole Blood', turnaroundTime: 'Same Day (3-4 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-002', slNo: 2, code: 'LFT', name: 'L.F.T', fullName: 'Liver Function Test (11 Parameters)', category: 'Biochemistry', price: 650, sampleType: 'Serum', turnaroundTime: 'Same Day (4-6 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-003', slNo: 3, code: 'KFT', name: 'K.F.T', fullName: 'Kidney Function Test (Renal Profile)', category: 'Biochemistry', price: 650, sampleType: 'Serum', turnaroundTime: 'Same Day (4-6 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-004', slNo: 4, code: 'LIPID', name: 'Lipid Profile', fullName: 'Complete Lipid Profile (Cholesterol, HDL, LDL, TG)', category: 'Biochemistry', price: 650, sampleType: 'Serum', turnaroundTime: 'Same Day (4-6 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-005', slNo: 5, code: 'HBA1C', name: 'HBA1C', fullName: 'Glycosylated Haemoglobin (3-Month Sugar)', category: 'Biochemistry', price: 700, sampleType: 'EDTA Whole Blood', turnaroundTime: 'Same Day (3-4 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-006', slNo: 6, code: 'HIV', name: 'HIV', fullName: 'HIV 1 & 2 Screening (Rapid / 4th Gen ELISA)', category: 'Serology', price: 300, sampleType: 'Serum', turnaroundTime: 'Same Day (2 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-007', slNo: 7, code: 'HBSAG', name: 'HBSAg', fullName: 'Hepatitis B Surface Antigen Rapid Screen', category: 'Serology', price: 250, sampleType: 'Serum', turnaroundTime: 'Same Day (2 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-008', slNo: 8, code: 'HCV', name: 'HCV', fullName: 'Hepatitis C Virus Antibody Screening', category: 'Serology', price: 300, sampleType: 'Serum', turnaroundTime: 'Same Day (2 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-009', slNo: 9, code: 'VDRL', name: 'VDRL', fullName: 'VDRL / RPR Syphilis Test', category: 'Serology', price: 150, sampleType: 'Serum', turnaroundTime: 'Same Day (2 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-010', slNo: 10, code: 'T3T4TSH', name: 'T3T4TSH', fullName: 'Complete Thyroid Profile (Total T3, Total T4, TSH)', category: 'Hormones', price: 550, sampleType: 'Serum', turnaroundTime: 'Same Day (4-6 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-011', slNo: 11, code: 'TSH', name: 'TSH', fullName: 'Thyroid Stimulating Hormone (Ultrasensitive)', category: 'Hormones', price: 300, sampleType: 'Serum', turnaroundTime: 'Same Day (3-4 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-012', slNo: 12, code: 'ABORH', name: 'ABORH', fullName: 'Blood Grouping & Rh Factor Typing', category: 'Haematology', price: 50, sampleType: 'EDTA Whole Blood', turnaroundTime: '1 Hour', fastingRequired: false, isAvailable: true },
  { id: 'test-013', slNo: 13, code: 'LH', name: 'LH', fullName: 'Luteinizing Hormone', category: 'Hormones', price: 600, sampleType: 'Serum', turnaroundTime: 'Same Day', fastingRequired: false, isAvailable: true },
  { id: 'test-014', slNo: 14, code: 'FSH', name: 'F.S.H', fullName: 'Follicle Stimulating Hormone', category: 'Hormones', price: 600, sampleType: 'Serum', turnaroundTime: 'Same Day', fastingRequired: false, isAvailable: true },
  { id: 'test-015', slNo: 15, code: 'PRL', name: 'PRL', fullName: 'Prolactin Hormone', category: 'Hormones', price: 600, sampleType: 'Serum', turnaroundTime: 'Same Day', fastingRequired: true, isAvailable: true },
  { id: 'test-016', slNo: 16, code: 'PCOD', name: 'PCOD', fullName: 'PCOD / PCOS Comprehensive Diagnostic Profile', category: 'Hormones', price: 3100, sampleType: 'Serum', turnaroundTime: '24-48 hrs', fastingRequired: true, isAvailable: true },
  { id: 'test-017', slNo: 17, code: 'AMH', name: 'A.M.H', fullName: 'Anti-Mullerian Hormone (Ovarian Reserve)', category: 'Hormones', price: 2100, sampleType: 'Serum', turnaroundTime: '24 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-018', slNo: 18, code: 'HB', name: 'Hb%', fullName: 'Haemoglobin Percentage (Hb%)', category: 'Haematology', price: 50, sampleType: 'EDTA Whole Blood', turnaroundTime: '30 Mins', fastingRequired: false, isAvailable: true },
  { id: 'test-019', slNo: 19, code: 'BTCT', name: 'BT CT', fullName: 'Bleeding Time & Clotting Time', category: 'Haematology', price: 100, sampleType: 'Fresh Capillary Blood', turnaroundTime: '30 Mins', fastingRequired: false, isAvailable: true },
  { id: 'test-020', slNo: 20, code: 'SS2', name: 'S.S - 2', fullName: 'Special Screening Package 2 (Metabolic & Organ)', category: 'Special Profiles', price: 1300, sampleType: 'Blood & Urine', turnaroundTime: 'Same Day', fastingRequired: true, isAvailable: true },
  { id: 'test-021', slNo: 21, code: 'SS1', name: 'S.S - 1', fullName: 'Special Screening Package 1 (Basic Health)', category: 'Special Profiles', price: 1000, sampleType: 'Blood & Urine', turnaroundTime: 'Same Day', fastingRequired: true, isAvailable: true },
  { id: 'test-022', slNo: 22, code: 'SS3', name: 'S.S - 3', fullName: 'Special Screening Package 3 (Comprehensive)', category: 'Special Profiles', price: 1900, sampleType: 'Blood & Urine', turnaroundTime: 'Same Day', fastingRequired: true, isAvailable: true },
  { id: 'test-023', slNo: 23, code: 'SS4', name: 'S.S - 4', fullName: 'Special Screening Package 4 (Executive Master)', category: 'Special Profiles', price: 2400, sampleType: 'Blood & Urine', turnaroundTime: 'Same Day', fastingRequired: true, isAvailable: true },
  { id: 'test-024', slNo: 24, code: 'UREA', name: 'UREA', fullName: 'Blood Urea / BUN', category: 'Biochemistry', price: 100, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-025', slNo: 25, code: 'CREATINE', name: 'CREATINE', fullName: 'Serum Creatinine (Renal Marker)', category: 'Biochemistry', price: 100, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-026', slNo: 26, code: 'URICACID', name: 'URIC ACID', fullName: 'Serum Uric Acid (Gout & Joint Health)', category: 'Biochemistry', price: 150, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  // Note: 27 and 28 missing on original image
  { id: 'test-029', slNo: 29, code: 'SGPT', name: 'SGPT', fullName: 'Serum Glutamic Pyruvic Transaminase (ALT)', category: 'Biochemistry', price: 150, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-030', slNo: 30, code: 'SGOT', name: 'SGOT', fullName: 'Serum Glutamic Oxaloacetic Transaminase (AST)', category: 'Biochemistry', price: 150, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-031', slNo: 31, code: 'BILRUBIN', name: 'BILRUBIN', fullName: 'Total, Direct & Indirect Bilirubin', category: 'Biochemistry', price: 150, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-032', slNo: 32, code: 'URINERE', name: 'URINE R/E', fullName: 'Urine Routine & Microscopic Examination', category: 'Fluid Analysis', price: 100, sampleType: 'Fresh Midstream Urine', turnaroundTime: '1-2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-033', slNo: 33, code: 'URINECS', name: 'URINE C/S', fullName: 'Urine Culture & Antibiotic Sensitivity (Aerobic)', category: 'Fluid Analysis', price: 200, sampleType: 'Sterile Midstream Urine', turnaroundTime: '48-72 hrs', fastingRequired: false, isAvailable: true },

  // Right Column from Price List Image
  { id: 'test-036', slNo: 36, code: 'BSF', name: 'BSF', fullName: 'Blood Sugar Fasting (8-10 hrs Fasting)', category: 'Biochemistry', price: 50, sampleType: 'Fluoride Plasma', turnaroundTime: '1-2 hrs', fastingRequired: true, isAvailable: true },
  { id: 'test-037', slNo: 37, code: 'BSPP', name: 'BSPP', fullName: 'Blood Sugar Post Prandial (2 hrs post meal)', category: 'Biochemistry', price: 50, sampleType: 'Fluoride Plasma', turnaroundTime: '1-2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-038', slNo: 38, code: 'BSR', name: 'BSR', fullName: 'Blood Sugar Random (Anytime Glucose)', category: 'Biochemistry', price: 50, sampleType: 'Fluoride Plasma', turnaroundTime: 'Instant (15 mins)', fastingRequired: false, isAvailable: true },
  { id: 'test-039', slNo: 39, code: 'ESR', name: 'ESR', fullName: 'Erythrocyte Sedimentation Rate (Westergren)', category: 'Haematology', price: 100, sampleType: 'Citrated Blood', turnaroundTime: '2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-040', slNo: 40, code: 'CPR', name: 'CPR', fullName: 'C-Reactive Protein (CRP Quantitative / Inflammation)', category: 'Immunology', price: 250, sampleType: 'Serum', turnaroundTime: '3-4 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-041', slNo: 41, code: 'RAFACTOR', name: 'RA FACTOR', fullName: 'Rheumatoid Arthritis Factor (Quantitative)', category: 'Immunology', price: 200, sampleType: 'Serum', turnaroundTime: '3-4 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-042', slNo: 42, code: 'ASOTITER', name: 'ASO TITER', fullName: 'Anti-Streptolysin O (ASO) Titer', category: 'Immunology', price: 200, sampleType: 'Serum', turnaroundTime: '3-4 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-043', slNo: 43, code: 'VITAMIND', name: 'VITAMIN D', fullName: '25-Hydroxy Vitamin D (Total D2 + D3)', category: 'Biochemistry', price: 1200, sampleType: 'Serum', turnaroundTime: 'Same Day (6 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-044', slNo: 44, code: 'VITAMINB12', name: 'VITAMIN B12', fullName: 'Cyanocobalamin / Active Vitamin B12', category: 'Biochemistry', price: 1000, sampleType: 'Serum', turnaroundTime: 'Same Day (6 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-045', slNo: 45, code: 'IRONPROFILE', name: 'IRON PROFILE', fullName: 'Complete Iron Profile (Serum Iron, TIBC, % Saturation)', category: 'Biochemistry', price: 700, sampleType: 'Serum', turnaroundTime: 'Same Day (6 hrs)', fastingRequired: true, isAvailable: true },
  { id: 'test-046', slNo: 46, code: 'TORCH10', name: 'TORCH 10', fullName: 'TORCH Profile 10 Parameters (IgG & IgM Panel)', category: 'Serology', price: 2700, sampleType: 'Serum', turnaroundTime: '24-48 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-047', slNo: 47, code: 'FNAC', name: 'FNAC', fullName: 'Fine Needle Aspiration Cytology (Palpable Swelling)', category: 'FNAC', price: 1600, sampleType: 'Cytology Aspirate', turnaroundTime: '24-48 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-048', slNo: 48, code: 'BIOPSY', name: 'BIOPSY', fullName: 'Histopathology Biopsy (Small/Medium Tissue)', category: 'Histopathology', price: 1400, sampleType: 'Formalin Tissue', turnaroundTime: '3-5 Days', fastingRequired: false, isAvailable: true },
  { id: 'test-049', slNo: 49, code: 'WIDAL', name: 'WIDAL', fullName: 'Widal Agglutination Slide / Tube Test', category: 'Serology', price: 200, sampleType: 'Serum', turnaroundTime: '2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-050', slNo: 50, code: 'MALARIA', name: 'MALARIA', fullName: 'Malaria Antigen Card & Smear Examination (MP)', category: 'Serology', price: 250, sampleType: 'EDTA Whole Blood', turnaroundTime: '1 hr', fastingRequired: false, isAvailable: true },
  { id: 'test-051', slNo: 51, code: 'TYPHOID', name: 'TYPHOID', fullName: 'Typhoid IgM / IgG (Typhi Dot Rapid)', category: 'Serology', price: 150, sampleType: 'Serum', turnaroundTime: '1-2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-052', slNo: 52, code: 'AFBSPUTUM', name: 'AFB(SPOTUM)', fullName: 'Acid Fast Bacilli Stain (Sputum for TB Examination)', category: 'Serology', price: 300, sampleType: 'Early Morning Sputum', turnaroundTime: 'Same Day (4 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-053', slNo: 53, code: 'PBS', name: 'PBS', fullName: 'Peripheral Blood Smear Examination (Cell Morphology)', category: 'Haematology', price: 300, sampleType: 'EDTA Blood Slide', turnaroundTime: '3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-054', slNo: 54, code: 'FALERIA', name: 'FALERIA', fullName: 'Filariasis Antigen / Microfilaria Nocturnal Smear', category: 'Serology', price: 900, sampleType: 'Night Blood Specimen', turnaroundTime: 'Same Day', fastingRequired: false, isAvailable: true },
  { id: 'test-055', slNo: 55, code: 'FRETTIN', name: 'FRETTIN', fullName: 'Serum Ferritin (Iron Storage Reserve)', category: 'Biochemistry', price: 500, sampleType: 'Serum', turnaroundTime: '4 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-056', slNo: 56, code: 'STOOLRE', name: 'STOOL R/E', fullName: 'Stool Routine & Microscopic Examination (Ova/Cyst)', category: 'Fluid Analysis', price: 150, sampleType: 'Fresh Stool Specimen', turnaroundTime: '2 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-057', slNo: 57, code: 'STOOLCS', name: 'STOOL C/S', fullName: 'Stool Culture & Sensitivity (Enteric Pathogens)', category: 'Fluid Analysis', price: 300, sampleType: 'Sterile Stool Specimen', turnaroundTime: '48-72 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-058', slNo: 58, code: 'ADA', name: 'ADA', fullName: 'Adenosine Deaminase Activity (Pleural/Ascitic/CSF)', category: 'Fluid Analysis', price: 900, sampleType: 'Body Fluid / Serum', turnaroundTime: '24 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-059', slNo: 59, code: 'TBGOLD', name: 'TB GOLD', fullName: 'Interferon Gamma Release Assay (TB Gold / IGRA)', category: 'Serology', price: 3100, sampleType: 'Special Heparinized Blood', turnaroundTime: '48-72 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-060', slNo: 60, code: 'CALCIUM', name: 'CALCIUM', fullName: 'Total Serum Calcium & Corrected Calcium', category: 'Biochemistry', price: 200, sampleType: 'Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-061', slNo: 61, code: 'PAPHPV', name: 'PAP HPV', fullName: 'Liquid-Based Cervical Cytology with High-Risk HPV DNA', category: 'Histopathology', price: 2500, sampleType: 'Liquid-Based Pap Vial', turnaroundTime: '3-5 Days', fastingRequired: false, isAvailable: true },
  { id: 'test-062', slNo: 62, code: 'PAPSAMER', name: 'PAP SAMER', fullName: 'Conventional Pap Smear Cervical Cytology', category: 'Histopathology', price: 1900, sampleType: 'Cervical / Vaginal Smear', turnaroundTime: '48 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-063', slNo: 63, code: 'ELECTROLYTE', name: 'ELECTROLYTE', fullName: 'Serum Electrolytes (Sodium, Potassium, Chloride)', category: 'Biochemistry', price: 600, sampleType: 'Plain Serum', turnaroundTime: '2-3 hrs', fastingRequired: false, isAvailable: true },
  { id: 'test-064', slNo: 64, code: 'IGETOTAL', name: 'IGE TOTAL', fullName: 'Total Serum Immunoglobulin E (Allergy Marker)', category: 'Immunology', price: 1200, sampleType: 'Serum', turnaroundTime: 'Same Day (6 hrs)', fastingRequired: false, isAvailable: true },
  { id: 'test-065', slNo: 65, code: 'MTMONTEX', name: 'MT(MONTEX)', fullName: 'Mantoux Tuberculin Skin Test (5 TU PPD)', category: 'Serology', price: 300, sampleType: 'Intradermal PPD Injection', turnaroundTime: '48-72 hrs Reading', fastingRequired: false, isAvailable: true },
  { id: 'test-066', slNo: 66, code: 'HBSAGDNA', name: 'HBsAG DNA', fullName: 'Hepatitis B Quantitative Real-Time PCR (Viral Load)', category: 'Serology', price: 6500, sampleType: 'EDTA Plasma', turnaroundTime: '3-5 Days', fastingRequired: false, isAvailable: true },
];

